
--SET IDENTITY_INSERT [Riverwatch].dbo.tblSample ON
insert into  [Riverwatch].[dbo].[Samples]
(
	[SampleID]
      ,[StationID]
      ,[OrganizationID]
      ,[SampleNumber]
      ,[NumberSample]
      ,[DateCollected]
      ,[TimeCollected]
      ,[DateReceived]
      ,[DataSheetIncluded]
      ,[MissingDataSheetReqDate]
      ,[ChainOfCustody]
      ,[MissingDataSheetReceived]
      ,[NoMetals]
      ,[PhysicalHabitat]
      ,[Bug]
      ,[NoNutrient]
      ,[TotalSuspendedSolids]
      ,[NitratePhosphorus]
      ,[DuplicatedTSS]
      ,[DuplicatedNP]
      ,[Comment]
      ,[DateCreated]
      ,[UserCreated]
      ,[DateLastModified]
      ,[UserLastModified]
      ,[ChlorideSulfate]
      ,[BlankMetals]
      ,[DuplicatedMetals]
      ,[BugsQA]
      ,[DuplicatedCS]
      ,[Valid]
	
)
 SELECT 
 	[SampleID]
  ,[StationID]
      ,[OrganizationID]
      ,[SampleNumber]
      ,[NumberSample]
      ,[DateCollected]
      ,[TimeCollected]
      ,[DateReceived]
      ,[DataSheetIncluded]
      ,[MissingDataSheetReqDate]
      ,[ChainOfCustody]
      ,[MissingDataSheetReceived]
      ,[NoMetals]
      ,[PhysicalHabitat]
      ,[Bug]
      ,[NoNutrient]
      ,[TotalSuspendedSolids]
      ,[NitratePhosphorus]
      ,[DuplicatedTSS]
      ,[DuplicatedNP]
      ,[Comment]
      ,[DateCreated]
      ,[UserCreated]
      ,[DateLastModified]
      ,[UserLastModified]
      ,[ChlorideSulfate]
      ,[BlankMetals]
      ,[DuplicatedMetals]
      ,[BugsQA]
      ,[DuplicatedCS]
      ,[Valid]
	 FROM [dbRiverwatchWaterData].[dbo].[tblSample]
		 
	 where  NumberSample not in 
  (
	select  [NumberSample]  from   [Riverwatch].[dbo].[Samples]
  ) 

 -- where code not in 
 -- (
	--select code  from   [RiverWatch].[dbo].[InboundICPOrigional]   
 -- )