
SET IDENTITY_INSERT [Riverwatch].dbo.orgStatus ON
insert into RiverWatch.dbo.orgStatus
(
[ID]
      ,[OrganizationID]
      ,[ContractStartDate]
      ,[ContractEndDate]
      ,[ContractSigned]
      ,[ContractSignedDate]
      ,[SiteVisited]
      ,[VolunteerTimeSheet1]
      ,[VolunteerTimeShee2]
      ,[VolunteerTimeSheet3]
      ,[VolunteerTimeSheet4]
      ,[DataEnteredElectronically1]
      ,[DataEnteredElectronically2]
      ,[DataEnteredElectronically3]
      ,[DataEnteredElectronically4]
      ,[SampleShipped1]
      ,[SampleShipped2]
      ,[SampleShipped3]
      ,[SampleShipped4]
      ,[NumberOfSamplesJan]
      ,[NumberOfSamplesFeb]
      ,[NumberOfSamplesMar]
      ,[NumberOfSamplesApr]
      ,[NumberOfSamplesMay]
      ,[NumberOfSamplesJun]
      ,[NumberOfSamplesJul]
      ,[NumberOfSamplesAug]
      ,[NumberOfSamplesSep]
      ,[NumberOfSamplesOct]
      ,[NumberOfSamplesNov]
      ,[NumberOfSamplesDec]
      ,[Nutrient1Collected]
      ,[Nutrient2Collected]
      ,[BugCollected]
      ,[UnknownSpringRecordedDate]
      ,[UnknownFallRecordedDate]
      ,[NumberOfSamplesBlank]
      ,[NumberOfSamplesDuplicate]
      ,[TroubleComment]
      ,[NoteComment]
      ,[HardshipComment]
      ,[DateCreated]
      ,[UserCreated]
      ,[DateLastModified]
      ,[UserLastModified]
      ,[NumberOfMetalsBlank]
      ,[NumberOfMetalsDuplicate]
	  )
select * 
  FROM [dbRiverwatchWaterData].[dbo].[tblStatus]

