//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWInbound2
{
    using System;
    using System.Collections.Generic;
    
    public partial class expStnMetal
    {
        public string ProjectID { get; set; }
        public Nullable<int> SampleID { get; set; }
        public string SampleNumber { get; set; }
        public Nullable<int> StationID { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> StationNum { get; set; }
        public Nullable<int> KitNum { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> CSampID { get; set; }
        public Nullable<int> Rep { get; set; }
        public Nullable<double> AL_D { get; set; }
        public Nullable<double> AL_T { get; set; }
        public Nullable<double> AS_D { get; set; }
        public Nullable<double> AS_T { get; set; }
        public Nullable<double> CA_D { get; set; }
        public Nullable<double> CA_T { get; set; }
        public Nullable<double> CD_D { get; set; }
        public Nullable<double> CD_T { get; set; }
        public Nullable<double> CU_D { get; set; }
        public Nullable<double> CU_T { get; set; }
        public Nullable<double> FE_D { get; set; }
        public Nullable<double> FE_T { get; set; }
        public Nullable<double> PB_D { get; set; }
        public Nullable<double> PB_T { get; set; }
        public Nullable<double> MG_D { get; set; }
        public Nullable<double> MG_T { get; set; }
        public Nullable<double> MN_D { get; set; }
        public Nullable<double> MN_T { get; set; }
        public Nullable<double> SE_D { get; set; }
        public Nullable<double> SE_T { get; set; }
        public Nullable<double> ZN_D { get; set; }
        public Nullable<double> ZN_T { get; set; }
        public Nullable<double> NA_D { get; set; }
        public Nullable<double> NA_T { get; set; }
        public Nullable<double> K_D { get; set; }
        public Nullable<double> K_T { get; set; }
        public string Comments { get; set; }
        public int ID { get; set; }
    }
}
