//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWInbound2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgStationsView
    {
        public Nullable<int> OrganizationID { get; set; }
        public string Organization { get; set; }
        public string StationName { get; set; }
        public Nullable<int> Number { get; set; }
        public string WaterCode { get; set; }
        public string WBID { get; set; }
        public string Description { get; set; }
        public string River { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<double> Lat { get; set; }
        public string County { get; set; }
        public string NearCity { get; set; }
        public Nullable<bool> USGS { get; set; }
        public Nullable<bool> StateEngineering { get; set; }
    }
}
