//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWInbound2
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAQCView
    {
        public string TypeCode { get; set; }
        public string SampleNumber { get; set; }
        public Nullable<decimal> AL_D { get; set; }
        public Nullable<decimal> AL_T { get; set; }
        public Nullable<decimal> AS_D { get; set; }
        public Nullable<decimal> AS_T { get; set; }
        public Nullable<decimal> CA_D { get; set; }
        public Nullable<decimal> CA_T { get; set; }
        public Nullable<decimal> CD_D { get; set; }
        public Nullable<decimal> CD_T { get; set; }
        public Nullable<decimal> CU_D { get; set; }
        public Nullable<decimal> CU_T { get; set; }
        public Nullable<decimal> FE_D { get; set; }
        public Nullable<decimal> FE_T { get; set; }
        public Nullable<decimal> MG_D { get; set; }
        public Nullable<decimal> MG_T { get; set; }
        public Nullable<decimal> MN_D { get; set; }
        public Nullable<decimal> MN_T { get; set; }
        public Nullable<decimal> PB_D { get; set; }
        public Nullable<decimal> PB_T { get; set; }
        public Nullable<decimal> SE_D { get; set; }
        public Nullable<decimal> SE_T { get; set; }
        public Nullable<decimal> ZN_D { get; set; }
        public Nullable<decimal> ZN_T { get; set; }
        public Nullable<decimal> NA_D { get; set; }
        public Nullable<decimal> NA_T { get; set; }
        public Nullable<decimal> K_D { get; set; }
        public Nullable<decimal> K_T { get; set; }
    }
}
