//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWInbound2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActivity
    {
        public int tvNODE { get; set; }
        public Nullable<int> tvPARENTNODE { get; set; }
        public string tvTEXT { get; set; }
        public string tvIMAGEURL { get; set; }
        public string tvDOCURL { get; set; }
        public Nullable<int> tvSORTORDER { get; set; }
    }
}
