//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWInbound2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBenTaxa
    {
        public tblBenTaxa()
        {
            this.tblBenthics = new HashSet<tblBenthic>();
        }
    
        public string FinalID { get; set; }
        public string TSN { get; set; }
        public string ParTSN { get; set; }
        public string Phylum { get; set; }
        public string Subphylum { get; set; }
        public string Class { get; set; }
        public string BOrder { get; set; }
        public string Family { get; set; }
        public string Tribe { get; set; }
        public string Genus { get; set; }
        public string Species { get; set; }
        public string Variety { get; set; }
        public string TaxaGroup { get; set; }
        public Nullable<int> TolVal { get; set; }
        public string FFG { get; set; }
        public string Habit { get; set; }
        public string LifeCycle { get; set; }
        public string InBenthics { get; set; }
        public string CharGroupID { get; set; }
        public string RowID { get; set; }
        public string VialNum { get; set; }
        public string PhotoLoc { get; set; }
        public Nullable<bool> AdminCheck { get; set; }
        public Nullable<System.DateTime> DateNameRevised { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public string Comments { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string UserLastModified { get; set; }
    
        public virtual ICollection<tblBenthic> tblBenthics { get; set; }
    }
}
