//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWInbound2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBenSamp
    {
        public tblBenSamp()
        {
            this.tblBenGrids = new HashSet<tblBenGrid>();
            this.tblBenReps = new HashSet<tblBenRep>();
        }
    
        public int ID { get; set; }
        public int SampleID { get; set; }
        public int ActivityID { get; set; }
        public Nullable<System.DateTime> CollDate { get; set; }
        public int CollMeth { get; set; }
        public int GearConfigID { get; set; }
        public Nullable<System.DateTime> CollTime { get; set; }
        public int Medium { get; set; }
        public int Intent { get; set; }
        public int Community { get; set; }
        public int BioResultGroupID { get; set; }
        public Nullable<int> NumKicksSamples { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<bool> Valid { get; set; }
        public int ActivityTypeID { get; set; }
        public int FieldGearID { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string UserLastModified { get; set; }
        public int LabCount { get; set; }
    
        public virtual ICollection<tblBenGrid> tblBenGrids { get; set; }
        public virtual tlkActivityType tlkActivityType { get; set; }
        public virtual tlkActivityCategory tlkActivityCategory { get; set; }
        public virtual tlkBioResultsType tlkBioResultsType { get; set; }
        public virtual tlkFieldProcedure tlkFieldProcedure { get; set; }
        public virtual tlkCommunity tlkCommunity { get; set; }
        public virtual tlkFieldGear tlkFieldGear { get; set; }
        public virtual tlkGearConfig tlkGearConfig { get; set; }
        public virtual tlkIntent tlkIntent { get; set; }
        public virtual tlkMedium tlkMedium { get; set; }
        public virtual ICollection<tblBenRep> tblBenReps { get; set; }
    }
}
