//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWInbound2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEquipment
    {
        public int ID { get; set; }
        public int OrganizationID { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> DateReJuv1 { get; set; }
        public Nullable<System.DateTime> DateReJuv2 { get; set; }
        public Nullable<System.DateTime> AutoReplaceDt { get; set; }
        public string Comment { get; set; }
    }
}
