//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWInbound2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhysHab
    {
        public int ID { get; set; }
        public Nullable<int> RepNum { get; set; }
        public Nullable<int> ParaID { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> SampleID { get; set; }
        public string StoretUploaded { get; set; }
        public Nullable<bool> Valid { get; set; }
    }
}
