//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWInbound2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStatu
    {
        public tblStatu()
        {
            this.tblStatusStations = new HashSet<tblStatusStation>();
        }
    
        public int StatusID { get; set; }
        public int OrganizationID { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public bool ContractSigned { get; set; }
        public Nullable<System.DateTime> ContractSignedDate { get; set; }
        public bool SiteVisited { get; set; }
        public bool VolunteerTimeSheet1 { get; set; }
        public bool VolunteerTimeShee2 { get; set; }
        public bool VolunteerTimeSheet3 { get; set; }
        public bool VolunteerTimeSheet4 { get; set; }
        public bool DataEnteredElectronically1 { get; set; }
        public bool DataEnteredElectronically2 { get; set; }
        public bool DataEnteredElectronically3 { get; set; }
        public bool DataEnteredElectronically4 { get; set; }
        public bool SampleShipped1 { get; set; }
        public bool SampleShipped2 { get; set; }
        public bool SampleShipped3 { get; set; }
        public bool SampleShipped4 { get; set; }
        public Nullable<byte> NumberOfSamplesJan { get; set; }
        public Nullable<byte> NumberOfSamplesFeb { get; set; }
        public Nullable<byte> NumberOfSamplesMar { get; set; }
        public Nullable<byte> NumberOfSamplesApr { get; set; }
        public Nullable<byte> NumberOfSamplesMay { get; set; }
        public Nullable<byte> NumberOfSamplesJun { get; set; }
        public Nullable<byte> NumberOfSamplesJul { get; set; }
        public Nullable<byte> NumberOfSamplesAug { get; set; }
        public Nullable<byte> NumberOfSamplesSep { get; set; }
        public Nullable<byte> NumberOfSamplesOct { get; set; }
        public Nullable<byte> NumberOfSamplesNov { get; set; }
        public Nullable<byte> NumberOfSamplesDec { get; set; }
        public bool Nutrient1Collected { get; set; }
        public bool Nutrient2Collected { get; set; }
        public bool BugCollected { get; set; }
        public Nullable<System.DateTime> UnknownSpringRecordedDate { get; set; }
        public Nullable<System.DateTime> UnknownFallRecordedDate { get; set; }
        public Nullable<byte> NumberOfSamplesBlank { get; set; }
        public Nullable<byte> NumberOfSamplesDuplicate { get; set; }
        public string TroubleComment { get; set; }
        public string NoteComment { get; set; }
        public string HardshipComment { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string UserLastModified { get; set; }
        public Nullable<int> NumberOfMetalsBlank { get; set; }
        public Nullable<int> NumberOfMetalsDuplicate { get; set; }
    
        public virtual tblOrganization tblOrganization { get; set; }
        public virtual ICollection<tblStatusStation> tblStatusStations { get; set; }
    }
}
