//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWInbound2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tlkGearConfig
    {
        public tlkGearConfig()
        {
            this.tblBenSamps = new HashSet<tblBenSamp>();
        }
    
        public int Code { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string UserLastModified { get; set; }
        public Nullable<bool> Valid { get; set; }
        public int ID { get; set; }
        public int FieldGearID { get; set; }
    
        public virtual ICollection<tblBenSamp> tblBenSamps { get; set; }
        public virtual tlkFieldGear tlkFieldGear { get; set; }
    }
}
