//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWInbound2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnknownResultsForOrgView
    {
        public Nullable<int> KitNumber { get; set; }
        public string OrganizationName { get; set; }
        public string SampleType { get; set; }
        public string SampleNumber { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<decimal> Value1 { get; set; }
        public Nullable<decimal> Value2 { get; set; }
        public Nullable<decimal> MeanValue { get; set; }
        public Nullable<decimal> TrueValue { get; set; }
        public Nullable<int> Round { get; set; }
        public Nullable<decimal> PctRecovery { get; set; }
    }
}
