//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWInbound2
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewAWQMSData
    {
        public string Event { get; set; }
        public string TypeCode { get; set; }
        public Nullable<System.DateTime> SampleDate { get; set; }
        public Nullable<int> StationNumber { get; set; }
        public Nullable<double> Ammonia { get; set; }
        public Nullable<double> Chloride { get; set; }
        public Nullable<decimal> AL_D { get; set; }
        public Nullable<decimal> AL_T { get; set; }
        public Nullable<decimal> AS_D { get; set; }
        public Nullable<decimal> AS_T { get; set; }
        public Nullable<decimal> CA_D { get; set; }
        public Nullable<decimal> CA_T { get; set; }
        public Nullable<decimal> CD_D { get; set; }
        public Nullable<decimal> CD_T { get; set; }
        public Nullable<decimal> CU_D { get; set; }
        public Nullable<decimal> CU_T { get; set; }
        public Nullable<decimal> FE_D { get; set; }
        public Nullable<decimal> FE_T { get; set; }
        public Nullable<decimal> MG_D { get; set; }
        public Nullable<decimal> MG_T { get; set; }
        public Nullable<decimal> MN_D { get; set; }
        public Nullable<decimal> MN_T { get; set; }
        public Nullable<decimal> PB_D { get; set; }
        public Nullable<decimal> PB_T { get; set; }
        public Nullable<decimal> SE_D { get; set; }
        public Nullable<decimal> SE_T { get; set; }
        public Nullable<decimal> ZN_D { get; set; }
        public Nullable<decimal> ZN_T { get; set; }
        public Nullable<decimal> NA_D { get; set; }
        public Nullable<decimal> NA_T { get; set; }
        public Nullable<decimal> K_D { get; set; }
        public Nullable<decimal> K_T { get; set; }
        public Nullable<double> ChlorophyllA { get; set; }
        public Nullable<double> DOC { get; set; }
        public Nullable<double> NN { get; set; }
        public Nullable<double> OP { get; set; }
        public Nullable<double> Sulfate { get; set; }
        public Nullable<double> totN { get; set; }
        public Nullable<double> totP { get; set; }
        public Nullable<double> TKN { get; set; }
        public Nullable<double> orgN { get; set; }
        public Nullable<double> TSS { get; set; }
        public bool Valid { get; set; }
        public string WaterBodyID { get; set; }
    }
}
